name: Deploy release on alwaysdata environment
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Flask app
        uses: appleboy/ssh-action@master
        with:
          host: ssh-etudiant.alwaysdata.net
          username: etudiant
          password: EPSI2024
          script: |
            cd $HOME/www/flask
            git fetch --all
            git reset --hard origin/main
